## NumPy Function

In [30]:
# Main Code
import numpy as np
import time

#### Creating the get_array_stats function:

In [31]:
# Beginning of Function
def get_array_stats(arr: np.ndarray[np.int64]): # Parameter is an Array of type NumPy Array
# only accepts 64bit integer arrays
    start_t = time.time() # Records Starting Time
    column_mean = np.mean(arr, axis = 0) # Calculates Means along 0 axis (Columns)
    column_std = np.std(arr, axis = 0) # Calculates Standard Deviation along 0 axis (Columns)
    array_min = np.amin(arr) # Finds he smallest number within the entire array
    array_max = np.amax(arr) # Finds the largest number within the entire array
    end_t = time.time() # Recrods End Time
    computation_time = end_t - start_t # Calculates time taken for computation
    return column_mean, column_std, array_min, array_max, computation_time # Returns all values packed in a tuple

#### Testing:

In [32]:
# Test Function Which Has parameters of Size
def test_function(row,col) -> None:
    random_array = np.random.randint(low=0, high=100000, size=(row,col))
    print(random_array)
    print()
    print("1. Mean (column-wise) 2. Standard deviation (column-wise) 3. Minimum value 4. Maximum value 5. Computation time")
    print()
    print(get_array_stats(random_array))

# Test for 10 x 10, 100 x 100, 100 x 1000
test_function(10,10)
print("-------")
test_function(100,100)
print("-------")
test_function(100,1000)



[[ 7413 98059  9823 15313 99836 51695 89924 74999 71516 73295]
 [65810 71712 58688 20671 69763 42736 60521 58787 10658 64931]
 [73550 41303 69883  8426 63518 68394 17216  4952 23026 44177]
 [82553 34686 49502 48653 81463 82892 83064 29795 94053 77341]
 [44158 52791 10884 99520 89677 53275 19022 56440 42029 90326]
 [86996 67342 18099 87606 56928 55482 82575 62928 51186 95792]
 [44014 29872 53426 21803 51774 23463 27302  9505 35128 84119]
 [85927 72674 76886 41138 31519 68710 48624 85928 76274 11620]
 [61561 97884 37160 87876 98387 31910 33154 77032 67814 69564]
 [33260 86846 25028 82692 33995 40394 28104 17459 72830 10468]]

1. Mean (column-wise) 2. Standard deviation (column-wise) 3. Minimum value 4. Maximum value 5. Computation time

(array([58524.2, 65316.9, 40937.9, 51369.8, 67686. , 51895.1, 48950.6,
       47782.5, 54451.4, 62163.3]), array([24687.21925937, 23713.8083211 , 23097.25939349, 33193.72275536,
       23416.51456131, 17188.73274823, 26763.23184221, 28318.67111024,
      